import type { Metadata } from "next";
import {
  Inter,
  Montserrat,
  Open_Sans,
  Poppins,
  Roboto,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import clsx from "clsx";

const font = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "vabarnabas - Varga Barnabas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          "flex flex-col items-center bg-background-primary text-white",
          font.className
        )}
      >
        <Navbar />
        <div className="w-full max-w-[1280px] px-6 pb-16 pt-20 md:px-8">
          {children}
        </div>
      </body>
    </html>
  );
}
